spring:
  application:
    name: pizzeria-service
  datasource:
    url: jdbc:h2:mem:pizzadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always   # executa schema.sql no boot
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      grupo11: DEBUG
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://name-server:8761/eureka/

app:
  rabbitmq:
    queue:
      name: delivery-requests
